in:
  type: mysql
  host: input1
  port: 3306
  database: input1
  user: root
  password: password
  table: "basket_ball_teams"
  select: "*"
  incremental: true
  incremental_columns: [id]
  SSL: true
  options:
    enabledTLSProtocols: TLSv1.2
filters:
  - type: column
    columns:
        - {name: name}
        - {name: birthday}
        - {name: height}
    add_columns:
      - {name: team, type: string, default: 'basketball'}
      - {name: origin_id, src: id}
      - {name: origin_created_at, type: timestamp, src: created_at}
    default_timezone: "Asia/Tokyo"
out:
  type: mysql
  host: output
  port: 3306
  # port: 3308
  database: output
  user: root
  password: password
  table: "allstars"
  mode: insert
  options:
    enabledTLSProtocols: TLSv1.2
